### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by amitsi** [amitsi/pluribus-ansible#105]
Provide proper examples with leaf, spine, wan

example 1: leaf spine
example 2:leaf, spine, wan
example 3: third party???

Instead of this example.....

 mail.example.com

 [webservers]
 foo.example.com
 bar.example.com

 [dbservers]
 serverone.example.com
 servertwo.example.com
 serverthree.example.com

**Comment by ramanujjaju** [comment]
Fixed [here](https://github.com/amitsi/pluribus-ansible/blob/master/README.md#inventory)
