### ISSUE TITLE
Running a Playbook with Vault

### ISSUE THREAD

**Issue by amitsi** [amitsi/pluribus-ansible#107]
Expand this....Provide different examples and why and in what scenario they are needed

--ask-pass

-K

-u pluribus

-vvv

how to log the output?

How to time it 

How to run it when ssh might be disconnected and log it (tee and nohup)

**Comment by ramanujjaju** [comment]
Fixed [here](https://github.com/amitsi/pluribus-ansible/blob/master/README.md#running-playbooks)
