### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by amitsi** [amitsi/pluribus-ansible#108]
Please provide a snapshot of how example config file will like after modifying the path for modules and host files

/etc/ansible/library/

**Comment by ramanujjaju** [comment]
We have config file sample [here](https://github.com/amitsi/pluribus-ansible/blob/master/ansible.cfg.sample) along with a link in [README](https://github.com/amitsi/pluribus-ansible#configuration-file). I'll include a small snapshot in the README section as well.

**Comment by ramanujjaju** [comment]
Fixed [here](https://github.com/amitsi/pluribus-ansible/blob/master/README.md#configuration-file)
