### ISSUE TITLE
Need   some  improvement in messages 

### ISSUE THREAD

**Issue by pdam** [amitsi/pluribus-ansible#118]
I  am   running the   playbook   for the    first   time  and  in   fabric creation I  see  the message  for   spine1  

Some  of  these  need  to change 

Issue1   
---

 " gui-spine1: EULA accepted ", 
    " gui-spine1: Joined fabric gui-fabric ", 
  " gui-spine1: Configured fabric control network to mgmt ", 
  " gui-spine1: STP disabled ", 
 " gui-spine1: Ports enabled ", 
 " gui-spine1: Toggled 40G ports to 10G ", 
  " gui-spine1: In-band ip has already been assigned "  => This is   misleading  should be   "Assigning in band ip "

Similartly  for  the other  nodes  

Issue2  
---

When  spine2    runs  I see   messages

 " gui-spine2: Already a part of fabric gui-fabric " .  This   in  not  very intuitive    and   should be  "joining  gui-fabric"

Issue3   
---
 " gui-spine2: EULA has already been accepted ",  This is    not  very intuitive    and   should be  "accepting    EULA"

**Comment by saptaktakalkar** [comment]
It has been fixed.
