### ISSUE TITLE
Switch name is not getting updated to the name specified in hosts file

### ISSUE THREAD

**Issue by ramanujjaju** [amitsi/pluribus-ansible#174]
This issue is to track and work on Bug 15724 opened by Pratik.

I found out why its not updating the switch name with the name given in hostfile.

In `pn_initial_ztp.py`:
```
def update_switch_names(module, switch_name):
    """
    Method to update switch names.
    :param module: The Ansible module to fetch input parameters.
    :param switch_name: Name to assign to the switch.
    :return: String describing switch name got modified or not.
    """
    cli = pn_cli(module)
    cli += ' switch-setup-show format switch-name '
    if switch_name in run_cli(module, cli).split()[1]:
        return ' Switch name is same as hostname! '
```
- This should be `if switch_name == run_cli(module, cli).split()[1]: `
    `run_cli(module, cli).split()[1]` returns 'gui-spine22' and the condition 'gui-spine2' in 'gui-spine22' will return True
    Hence it is not changing the switch name here.

**Comment by saptaktakalkar** [comment]
@ramanujjaju Fixed here: https://github.com/amitsi/pluribus-ansible/pull/175
