### ISSUE TITLE
Ansible Hangs if CLI is not up

### ISSUE THREAD

**Issue by KyroChi** [amitsi/pluribus-ansible#207]
Ansible will hang if the CLI hasn't been set up. As in EULA accepted, password entered ect. Not sure if we should even attempt to fix this? Is it a reasonable expectation that all of that stuff will be set up before Ansible is run? Thanks :)

**Comment by saptaktakalkar** [comment]
@KyroChi This is not an issue. It is expected that CLI is up before we run the playbook. Even if we do switch-config-reset, we wait until CLI is up and then only we run the playbook. Hope this helps.
