### ISSUE TITLE
Possible workaround for bug 17587

### ISSUE THREAD

**Issue by ramanujjaju** [amitsi/pluribus-ansible#321]
Tried multiple runs, did not encounter the issue. Have a 3-5 second sleep here. 
https://github.com/amitsi/pluribus-ansible/blob/2dea2e42a4ffd81018a2d730c5a4608434278d35/ansible/pn_paramiko.py#L272
```
.
import time
.
.
    time.sleep(3)
    return ssh
```

**Comment by amitsi** [comment]
@ramanujjaju so on a 6 switch setup you have added 18 additional seconds and there is no certainty 3 seconds will help every time @ashxjain can you check what change in nvOS could be causing this issue?

**Comment by ramanujjaju** [comment]
Yeah the delay is definitely not good but this is just a workaround for the remote_tmp permission issues. I'm looking at '-q'(quiet) option for paramiko. Changing the remote_tmp in ansible.cfg didn't help. Also, the bug where banner gets printed twice is fixed on 2.6.1 gate. That can partly help with this issue.

**Comment by amitsi** [comment]
@ramanujjaju let @ashxjain ashish respond, if he says there is no other way, lets take this in but document it accordingly, to be removed for 2.6.1 (2.4.X VCF)

**Comment by ashxjain** [comment]
@amitsi Yes, we do need a sleep there but 1 second should be find.

**Comment by ashxjain** [comment]
@ramanujjaju Here at line 315:

`            chan.exec_command("shell %s" % cmd)
`
Change it to:

`            chan.exec_command("--quiet shell %s" % cmd)
`

**Comment by ashxjain** [comment]
This issue is now fixed.
