### ISSUE TITLE
Need   to have   switch   names   next  to  vlag   creation  

### ISSUE THREAD

**Issue by pdam** [amitsi/pluribus-ansible#58]
Right now    everything  seems   to happen at   gui-spine1 .  
We need   to have a   mechanism  to  show  local  vlag  creation  like  

    <switch>  <vlag_name> vlag configured successfully! 
Current   o/p  from  ansible-playbook -i hosts gui_l2_vrrp.yml  -u pluribus --ask-pass --ask-vault-pass -K

----

ok: [gui-spine1] => {
    "ztp_l2_out.stdout_lines": [
        " 172.16.0.1/24 has been already assigned to gui-leaf1!  172.16.0.2/24 has been already assigned to gui-leaf2!  172.16.0.3/24 has been already assigned to gui-leaf3!  172.16.0.4/24 has been already assigned to gui-leaf4!  172.16.0.5/24 has been already assigned to gui-spine1!  172.16.0.6/24 has been already assigned to gui-spine2!  spine-cluster created successfully!  gui-leaf1-to-gui-leaf2-cluster created successfully!  gui-leaf1-gui-leaf2-to-spine vlag configured successfully!  gui-spine1-gui-spine2-to-gui-leaf1gui-leaf2 vlag configured successfully! gui-leaf3-to-gui-spine1gui-spine2 gui-spine1-gui-spine2-to-gui-leaf3 vlag configured successfully! gui-leaf4-to-gui-spine1gui-spine2 gui-spine1-gui-spine2-to-gui-leaf4 vlag configured successfully!  STP enabled! "
    ]
}

**Comment by pdam** [comment]
There  are  other  places  as  well we  want to  mention the  switch  name  is  some  formatted   way that  can be  parsed

root@amitsi:~/ashish/pluribus-ansible/ansible/playbooks/advance# ansible-playbook -i hosts gui_l3_ztp.yml -u pluribus --ask-pass --ask-vault-pass -K 
SSH password: 
SUDO password[defaults to SSH password]: 
Vault password: 

PLAY [Zero Touch Provisioning - Layer3 setup] **********************************

TASK [Auto configure link IPs] *************************************************
changed: [gui-spine1]

TASK [debug] *******************************************************************
ok: [gui-spine1] => {
    "ztp_l3_out.stdout_lines": [
        " Created vrouter gui-spine2-vrouter on switch gui-spine2  Created vrouter gui-spine1-vrouter on switch gui-spine1  Created vrouter gui-leaf4-vrouter on switch gui-leaf4  Created vrouter gui-leaf3-vrouter on switch gui-leaf3  Created vrouter gui-leaf2-vrouter on switch gui-leaf2  Created vrouter gui-leaf1-vrouter on switch gui-leaf1  Added vrouter interface with ip 172.168.1.1/30 on gui-leaf1!  Added BFD config to gui-leaf1-vrouter  Added vrouter interface with ip 172.168.1.2/30 on gui-spine1!  Added BFD config to gui-spine1-vrouter  Added vrouter interface with ip 172.168.1.5/30 on gui-leaf2!  Added BFD config to gui-leaf2-vrouter  Added vrouter interface with ip 172.168.1.6/30 on gui-spine1!  Added BFD config to gui-spine1-vrouter  Added vrouter interface with ip 172.168.1.9/30 on gui-leaf3!  Added BFD config to gui-leaf3-vrouter  Added vrouter interface with ip 172.168.1.10/30 on gui-spine1!  Added BFD config to gui-spine1-vrouter  Added vrouter interface with ip 172.168.1.13/30 on gui-leaf4!  Added BFD config to gui-leaf4-vrouter  Added vrouter interface with ip 172.168.1.14/30 on gui-spine1!  Added BFD config to gui-spine1-vrouter  Added vrouter interface with ip 172.168.1.17/30 on gui-leaf1!  Added BFD config to gui-leaf1-vrouter  Added vrouter interface with ip 172.168.1.18/30 on gui-spine2!  Added BFD config to gui-spine2-vrouter  Added vrouter interface with ip 172.168.1.21/30 on gui-leaf2!  Added BFD config to gui-leaf2-vrouter  Added vrouter interface with ip 172.168.1.22/30 on gui-spine2!  Added BFD config to gui-spine2-vrouter  Added vrouter interface with ip 172.168.1.25/30 on gui-leaf3!  Added BFD config to gui-leaf3-vrouter  Added vrouter interface with ip 172.168.1.26/30 on gui-spine2!  **Added BFD config to gui-spine2-vrouter  Added vrouter interface with ip 172.168.1.29/30 on gui-leaf4!**  **Added BFD config to gui-leaf4-vrouter  Added vrouter interface with ip 172.168.1.30/30 on gui-spine2!**  Added BFD config to gui-spine2-vrouter  Added loopback ip 109.109.109.1 to gui-spine2-vrouter!  Added loopback ip 109.109.109.2 to gui-spine1-vrouter!  Added loopback ip 109.109.109.3 to gui-leaf4-vrouter!  Added loopback ip 109.109.109.4 to gui-leaf3-vrouter!  Added loopback ip 109.109.109.5 to gui-leaf2-vrouter!  Added loopback ip 109.109.109.6 to gui-leaf1-vrouter!  STP enabled! "
    ]
}

**Comment by saptaktakalkar** [comment]
@pdam Let us know the exact format you want.
Should it be `<switch>  <vlag_name> vlag configured successfully! `
or should it be `<vlag_name> vlag on <switch_name>configured successfully! ` ?

**Comment by saptaktakalkar** [comment]
Also for `BFD` config, let us know the exact format

**Comment by ramanujjaju** [comment]
Suggestion: If only the switch name which is being configured is needed, we can have the output message to begin with that switch name. We can have a parameter `pn_current_switch`  like the one being used in [pn_initial_ztp.py](https://github.com/amitsi/pluribus-ansible/blob/2e3e28a4df7174080dc8f63c506697196194648c/ansible/library/pn_initial_ztp.py)

**Comment by saptaktakalkar** [comment]
Fixed [here](https://github.com/amitsi/pluribus-ansible/pull/65).
Now, switch name will appear before every output message.
Examples: 
- <switch_name>: vlag configured successfully!
- <switch_name>: Added BFD config to <vrouter_name>
