### ISSUE TITLE
While   running the    fabric  creation playbooks  the  INband IP keeps  on changing as  the code   runs thru the  nodes 

### ISSUE THREAD

**Issue by pdam** [amitsi/pluribus-ansible#59]
The  Inband IP   assignments  messages  look   flaky  to me . As   it loops  the  assigned  in  band IP seems  to keep  on changing 

root@amitsi:~/ashish/pluribus-ansible/ansible/playbooks/advance# ansible-playbook -i hosts gui_fabric_creation.yml  -u pluribus --ask-pass --ask-vault-pass -K

TASK [debug] *******************************************************************
ok: [gui-spine1] => {
    "ztp_out.stdout_lines": [
        " EULA accepted on gui-spine1!  gui-spine1 has joined fabric ztp-fabric!  Configured fabric control network to mgmt on gui-spine1!  STP disabled on gui-spine1!  Ports enabled on gui-spine1!  Toggled 40G ports to 10G on gui-spine1!  **Assigned in-band ip 172.16.0.1/24 to gui-spine1!** "
    ]
}

TASK [debug] *******************************************************************
ok: [gui-spine2] => {
    "ztp_out.stdout_lines": [
        " EULA accepted on gui-spine2!  gui-spine2 has joined fabric ztp-fabric!  Fabric is already in mgmt control network  STP disabled on gui-spine2!  Ports enabled on gui-spine2!  Toggled 40G ports to 10G on gui-spine2!  172.16.0.1/24 has been already assigned to gui-spine1!  Assigned in-band ip 172.16.0.2/24 to gui-spine2! "
    ]
}
TASK [debug] *******************************************************************
ok: [gui-leaf1] => {
    "ztp_out.stdout_lines": [
        " EULA accepted on gui-leaf1!  gui-leaf1 has joined fabric ztp-fabric!  Fabric is already in mgmt control network  STP disabled on gui-leaf1!  Ports enabled on gui-leaf1!  Toggled 40G ports to 10G on gui-leaf1!  172.16.0.1/24 has been already assigned to gui-leaf1!  **Assigned in-band ip 172.16.0.3/24 to gui-spine1!**  Assigned in-band ip 172.16.0.4/24 to gui-spine2! "
    ]
}

TASK [debug] *******************************************************************
ok: [gui-leaf2] => {
    "ztp_out.stdout_lines": [
        " EULA accepted on gui-leaf2!  gui-leaf2 has joined fabric ztp-fabric!  Fabric is already in mgmt control network  STP disabled on gui-leaf2!  Ports enabled on gui-leaf2!  Toggled 40G ports to 10G on gui-leaf2!  172.16.0.1/24 has been already assigned to gui-leaf1!  172.16.0.2/24 has been already assigned to gui-leaf2!  **172.16.0.3/24 has been already assigned to gui-spine1!**  172.16.0.4/24 has been already assigned to gui-spine2! "
    ]
}

TASK [debug] *******************************************************************
ok: [gui-leaf3] => {
    "ztp_out.stdout_lines": [
        " EULA accepted on gui-leaf3!  gui-leaf3 has joined fabric ztp-fabric!  Fabric is already in mgmt control network  STP disabled on gui-leaf3!  Ports enabled on gui-leaf3!  Toggled 40G ports to 10G on gui-leaf3!  172.16.0.1/24 has been already assigned to gui-leaf1!  172.16.0.2/24 has been already assigned to gui-leaf2!  172.16.0.3/24 has been already assigned to gui-leaf3!  Assigned in-band ip 172.16.0.5/24 to gui-spine1!  Assigned in-band ip 172.16.0.6/24 to gui-spine2! "
    ]
}

TASK [pause] *******************************************************************
Pausing for 2 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [gui-leaf3]

PLAY [Zero Touch Provisioning - Initial setup] *********************************

TASK [Auto accept EULA, Disable STP, enable ports and create/join fabric] ******
changed: [gui-leaf4]

TASK [debug] *******************************************************************
ok: [gui-leaf4] => {
    "ztp_out.stdout_lines": [
        " EULA accepted on gui-leaf4!  gui-leaf4 has joined fabric ztp-fabric!  Fabric is already in mgmt control network  STP disabled on gui-leaf4!  Ports enabled on gui-leaf4!  Toggled 40G ports to 10G on gui-leaf4!  172.16.0.1/24 has been already assigned to gui-leaf1!  172.16.0.2/24 has been already assigned to gui-leaf2!  172.16.0.3/24 has been already assigned to gui-leaf3!  172.16.0.4/24 has been already assigned to gui-leaf4!  172.16.0.5/24 has been already assigned to gui-spine1!  172.16.0.6/24 has been already assigned to gui-spine2! "
    ]
}

TASK [pause] *******************************************************************
Pausing for 2 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [gui-leaf4]

PLAY RECAP *********************************************************************
gui-leaf1                  : ok=3    changed=1    unreachable=0    failed=0  
gui-leaf2                  : ok=3    changed=1    unreachable=0    failed=0  
gui-leaf3                  : ok=3    changed=1    unreachable=0    failed=0  
gui-leaf4                  : ok=3    changed=1    unreachable=0    failed=0  
gui-spine1                 : ok=3    changed=1    unreachable=0    failed=0  
gui-spine2                 : ok=3    changed=1    unreachable=0    failed=0

**Comment by saptaktakalkar** [comment]
@pdam Thanks for reporting. It has been fixed in this PR: https://github.com/amitsi/pluribus-ansible/pull/57
