### ISSUE TITLE
Remove the   inband IP  already created      messages   from   vlag  creation to avoid   clutter

### ISSUE THREAD

**Issue by pdam** [amitsi/pluribus-ansible#60]
Remove the   bolded    message   from   vlag  creation 
root@amitsi:~/ashish/pluribus-ansible/ansible/playbooks/advance# ansible-playbook -i hosts gui_l2_vrrp.yml  -u pluribus --ask-pass --ask-vault-pass -K

ok: [gui-spine1] => {
    "ztp_l2_out.stdout_lines": [
        " **172.16.0.1/24 has been already assigned to gui-leaf1!  172.16.0.2/24 has been already assigned to gui-leaf2!  172.16.0.3/24 has been already assigned to gui-leaf3!  172.16.0.4/24 has been already assigned to gui-leaf4!  172.16.0.5/24 has been already assigned to gui-spine1!  172.16.0.6/24 has been already assigned to gui-spine2!**  spine-cluster created successfully!  gui-leaf1-to-gui-leaf2-cluster created successfully!  gui-leaf1-gui-leaf2-to-spine vlag configured successfully!  gui-spine1-gui-spine2-to-gui-leaf1gui-leaf2 vlag configured successfully! gui-leaf3-to-gui-spine1gui-spine2 gui-spine1-gui-spine2-to-gui-leaf3 vlag configured successfully! gui-leaf4-to-gui-spine1gui-spine2 gui-spine1-gui-spine2-to-gui-leaf4 vlag configured successfully!  STP enabled! "
    ]
}

**Comment by saptaktakalkar** [comment]
@pdam It has been fixed already. Request you to use the latest code from the Master.
