### ISSUE TITLE
please    fix   playbook  pluribus-ansible/ansible/playbooks/advance/gui_l3_vrrp.yml

### ISSUE THREAD

**Issue by pdam** [amitsi/pluribus-ansible#61]
ansible-playbook -i hosts gui_l3_vrrp.yml -u pluribus --ask-pass --ask-vault-pass -K 
SSH password: 
SUDO password[defaults to SSH password]: 
Vault password: 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/ashish/pluribus-ansible/ansible/playbooks/advance/gui_l3_vrrp.yml': line 102, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Configure eBGP/OSPF
      ^ here

The error appears to have been in '/root/ashish/pluribus-ansible/ansible/playbooks/advance/gui_l3_vrrp.yml': line 102, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Configure eBGP/OSPF
      ^ here

**Comment by saptaktakalkar** [comment]
Fixed. Check now.

**Comment by saptaktakalkar** [comment]
The required module was not present on the machine. It has been put now. Please confirm and close the issue.
