### ISSUE TITLE
L2 or L3 VRRP playbooks  where  a  fixed no of nodes  are  required  should   detect hosts   file  and  refuse  Execuring playbooks if it cannot  run so 

### ISSUE THREAD

**Issue by pdam** [amitsi/pluribus-ansible#62]
This   would be  useful  for   winsoft  Integration  and  standalone  both if  we can detect  cases   where  we  cannot  run as  the no of  hosts  are  less  

e.g   1  spine  and  x  leaf 
  or   x  leafs  and  no  spine 
  etc   and  not  run the  playbook

**Comment by saptaktakalkar** [comment]
We have added a check to validate the number of spines and leafs for both L2 and L3 VRRP playbooks. Here is the pull request: https://github.com/amitsi/pluribus-ansible/pull/65
