### ISSUE TITLE
Error on running fabric creation playbook, also failed is still set to 0

### ISSUE THREAD

**Issue by ashxjain** [amitsi/pluribus-ansible#77]
I am getting following error on all switches while running fabric creation yaml file.

fatal: [gui-leaf4]: FAILED! => {"attempts": 3, "changed": false, "failed": true, "module_stderr": "Shared connection to 10.9.21.65 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Zut680/ansible_module_pn_initial_ztp.py\", line 626, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Zut680/ansible_module_pn_initial_ztp.py\", line 568, in main\r\n    if 'Success' in configure_control_network(module, control_network):\r\nTypeError: argument of type 'NoneType' is not iterable\r\n", "msg": "MODULE FAILURE"}

But the interesting thing is that the final status is 
PLAY RECAP *********************************************************************
gui-leaf1                  : ok=4    changed=0    unreachable=0    failed=0   
gui-leaf2                  : ok=4    changed=0    unreachable=0    failed=0   
gui-leaf3                  : ok=4    changed=0    unreachable=0    failed=0   
gui-leaf4                  : ok=4    changed=0    unreachable=0    failed=0   
gui-spine1                : ok=4    changed=0    unreachable=0    failed=0   
gui-spine2                : ok=4    changed=0    unreachable=0    failed=0

**Comment by saptaktakalkar** [comment]
@ashxjain It has been fixed already. Please pull the latest code.

**Comment by saptaktakalkar** [comment]
Closing the issue since it has been fixed already in this [commit](https://github.com/amitsi/pluribus-ansible/commit/3e3262de8def65e9ebf5d0682297bb50d953b7e3)
